
-- Insert sample A2A agents into the agents table
INSERT INTO agents (
  name, 
  description, 
  provider, 
  categories, 
  skills, 
  github_url,
  endpoint,
  documentation,
  is_verified,
  featured,
  votes
) VALUES
-- Python Agents
(
  'Google ADK',
  'Expense report filling agent, showcasing multi-turn interactions and web form handling. Perfect for automating expense reporting workflows with intelligent form completion.',
  'Google',
  ARRAY['Productivity', 'Finance', 'Automation'],
  ARRAY['expense reporting', 'form filling', 'multi-turn interaction', 'web automation', 'workflow management'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/google_adk',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/google_adk/README.md',
  true,
  true,
  45
),
(
  'AG2 + MCP',
  'MCP-enabled agent based on AG2 framework. Combines the power of AG2 with Model Context Protocol for enhanced agent capabilities.',
  'AG2',
  ARRAY['Development', 'Integration'],
  ARRAY['MCP protocol', 'AG2 framework', 'model context', 'agent development', 'integration'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/ag2',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/ag2/README.md',
  true,
  true,
  38
),
(
  'Azure AI Foundry',
  'Agent based on Azure AI Foundry services. Leverages Microsoft Azure AI capabilities for enterprise-grade agent solutions.',
  'Microsoft',
  ARRAY['Enterprise', 'Cloud', 'AI Services'],
  ARRAY['Azure AI', 'cloud services', 'enterprise AI', 'Microsoft ecosystem', 'foundry services'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/azureaifoundry_sdk',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/azureaifoundry_sdk/README.md',
  true,
  true,
  42
),
(
  'LangGraph Currency Converter',
  'Currency conversion agent with tool usage and streaming updates. Built with LangGraph for reliable financial data processing.',
  'LangChain',
  ARRAY['Finance', 'Data Analysis', 'Tools'],
  ARRAY['currency conversion', 'financial data', 'streaming updates', 'tool usage', 'LangGraph', 'real-time data'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/langgraph',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/langgraph/README.md',
  true,
  true,
  51
),
(
  'CrewAI Image Generator',
  'Image generation agent with multi-turn interactions and image transmission. Powered by CrewAI for collaborative image creation workflows.',
  'CrewAI',
  ARRAY['Content Creation', 'Image Generation', 'Creative'],
  ARRAY['image generation', 'multi-turn interaction', 'image transmission', 'creative workflows', 'CrewAI', 'visual content'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/crewai',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/crewai/README.md',
  true,
  true,
  47
),
(
  'LlamaIndex File Chat',
  'File parsing and chat agent with file upload and streaming updates. Uses LlamaIndex for intelligent document processing and chat.',
  'LlamaIndex',
  ARRAY['Document Processing', 'Chat', 'File Management'],
  ARRAY['file parsing', 'document chat', 'file upload', 'streaming updates', 'LlamaIndex', 'document intelligence'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/llama_index_file_chat',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/llama_index_file_chat/README.md',
  true,
  true,
  44
),
(
  'Marvin Contact Extractor',
  'Contact information extraction agent. Specialized in parsing and extracting contact details from various document formats.',
  'Marvin',
  ARRAY['Data Extraction', 'Contact Management', 'Document Processing'],
  ARRAY['contact extraction', 'information parsing', 'document processing', 'data extraction', 'contact management'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/marvin',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/marvin/README.md',
  true,
  false,
  33
),
(
  'MindsDB Enterprise Data',
  'Enterprise data agent supporting database queries. Connects to various databases for intelligent data analysis and reporting.',
  'MindsDB',
  ARRAY['Enterprise', 'Database', 'Data Analysis'],
  ARRAY['database queries', 'enterprise data', 'data analysis', 'SQL integration', 'business intelligence'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/mindsdb',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/mindsdb/README.md',
  true,
  true,
  39
),
(
  'Semantic Kernel Travel Agent',
  'Travel agent based on Microsoft Semantic Kernel framework. Provides intelligent travel planning and booking assistance.',
  'Microsoft',
  ARRAY['Travel', 'Planning', 'Microsoft'],
  ARRAY['travel planning', 'booking assistance', 'Semantic Kernel', 'Microsoft framework', 'travel automation'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/semantickernel',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/semantickernel/README.md',
  true,
  true,
  41
),
(
  'AutoGen Framework',
  'AutoGen framework example demonstrating multi-agent conversations and collaborative problem solving.',
  'Microsoft',
  ARRAY['Framework', 'Multi-Agent', 'Collaboration'],
  ARRAY['AutoGen', 'multi-agent systems', 'collaborative AI', 'conversation management', 'framework example'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/autogen',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/autogen/README.md',
  true,
  true,
  48
),
(
  'Hello World Agent',
  'Basic example agent demonstrating fundamental A2A protocol implementation. Perfect starting point for new developers.',
  'A2A Community',
  ARRAY['Getting Started', 'Examples', 'Tutorial'],
  ARRAY['basic example', 'getting started', 'A2A protocol', 'tutorial', 'beginner friendly'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/helloworld',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/helloworld/README.md',
  true,
  false,
  28
),
(
  'Veo Video Generator',
  'Video generation agent creating high-quality videos from text prompts. Powered by Google Veo technology.',
  'Google',
  ARRAY['Video Generation', 'Content Creation', 'AI Generation'],
  ARRAY['video generation', 'text-to-video', 'Veo technology', 'content creation', 'media generation'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/veo_video_gen',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/veo_video_gen/README.md',
  true,
  true,
  52
),
(
  'Analytics Agent',
  'Comprehensive analytics agent for data insights and reporting. Provides detailed analytics and visualization capabilities.',
  'A2A Community',
  ARRAY['Analytics', 'Data Analysis', 'Reporting'],
  ARRAY['data analytics', 'insights generation', 'reporting', 'data visualization', 'business analytics'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/analytics',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/analytics/README.md',
  true,
  false,
  35
),
(
  'A2A Telemetry',
  'Telemetry data agent for monitoring and performance tracking. Collects and analyzes system telemetry data.',
  'A2A Community',
  ARRAY['Monitoring', 'Telemetry', 'Performance'],
  ARRAY['telemetry data', 'monitoring', 'performance tracking', 'system analytics', 'observability'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/a2a_telemetry',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/a2a_telemetry/README.md',
  true,
  false,
  31
),
(
  'A2A MCP Agent',
  'MCP protocol agent demonstrating Model Context Protocol integration with A2A framework.',
  'A2A Community',
  ARRAY['Protocol', 'Integration', 'MCP'],
  ARRAY['MCP protocol', 'model context', 'protocol integration', 'A2A framework', 'context management'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/a2a_mcp',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/a2a_mcp/README.md',
  true,
  false,
  29
),
(
  'Birthday Planner ADK',
  'Birthday planning agent helping organize and plan birthday celebrations with intelligent suggestions.',
  'Google',
  ARRAY['Planning', 'Events', 'Personal Assistant'],
  ARRAY['birthday planning', 'event organization', 'celebration planning', 'personal assistant', 'event management'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/birthday_planner_adk',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/birthday_planner_adk/README.md',
  true,
  false,
  26
),
(
  'Headless Agent Auth',
  'Headless agent authentication example demonstrating secure authentication patterns for A2A agents.',
  'A2A Community',
  ARRAY['Authentication', 'Security', 'Examples'],
  ARRAY['headless authentication', 'security patterns', 'auth examples', 'secure agents', 'authentication flow'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/headless_agent_auth',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/headless_agent_auth/README.md',
  true,
  false,
  24
),
-- JavaScript/TypeScript Agents
(
  'Movie Agent',
  'Movie information search agent using TMDB API. Find detailed movie information, ratings, and recommendations.',
  'TMDB',
  ARRAY['Entertainment', 'Search', 'API Integration'],
  ARRAY['movie search', 'TMDB API', 'entertainment data', 'movie recommendations', 'film information'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/js/src/agents/movie-agent',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/js/src/agents/movie-agent/README.md',
  true,
  false,
  32
),
(
  'Coder Agent',
  'Code generation agent for JavaScript and TypeScript. Generate, review, and optimize code with AI assistance.',
  'A2A Community',
  ARRAY['Development', 'Code Generation', 'Programming'],
  ARRAY['code generation', 'JavaScript', 'TypeScript', 'programming assistance', 'code optimization'],
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/js/src/agents/coder',
  null,
  'https://github.com/google-a2a/a2a-samples/tree/main/samples/js/src/agents/coder/README.md',
  true,
  false,
  37
);
