
-- First, let's check what MCP servers we currently have to identify duplicates
-- Then add the new unique MCP servers

-- Add new MCP servers that aren't already in the database
INSERT INTO public.mcp_servers (name, description, provider, categories, github_url, package_name, repository_url) VALUES

-- Multi-App/Unified Access servers
('AnyQuery SQL Interface', 'Query more than 40 apps with one binary using SQL. Connect to PostgreSQL, MySQL, SQLite and more. Local-first and private by design.', 'julien040', ARRAY['Multi-App Access', 'Database'], 'https://github.com/julien040/anyquery', 'julien040/anyquery', 'https://github.com/julien040/anyquery'),
('MetaMCP Unified Middleware', 'Unified middleware MCP server that manages your MCP connections with GUI interface', 'metatool-ai', ARRAY['Multi-App Access', 'Management'], 'https://github.com/metatool-ai/metatool-app', 'metatool-ai/metatool-app', 'https://github.com/metatool-ai/metatool-app'),
('MindsDB Unified Platform', 'Connect and unify data across various platforms and databases with MindsDB as a single MCP server', 'mindsdb', ARRAY['Multi-App Access', 'AI/ML'], 'https://github.com/mindsdb/mindsdb', 'mindsdb/mindsdb', 'https://github.com/mindsdb/mindsdb'),
('MCP Server Registry', 'A list of MCP servers so you can ask your client which servers you can use to improve your workflow', 'glenngillen', ARRAY['Multi-App Access', 'Registry'], 'https://github.com/glenngillen/mcpmcp-server', 'glenngillen/mcpmcp-server', 'https://github.com/glenngillen/mcpmcp-server'),
('Open MCP Registry', 'Turn a web API into an MCP server in 10 seconds and add it to the open source registry', 'wegotdocs', ARRAY['Multi-App Access', 'API Integration'], 'https://github.com/wegotdocs/open-mcp', 'wegotdocs/open-mcp', 'https://github.com/wegotdocs/open-mcp'),
('Pipedream API Connector', 'Connect with 2,500 APIs with 8,000+ prebuilt tools, and manage servers for your users', 'PipedreamHQ', ARRAY['Multi-App Access', 'API Integration'], 'https://github.com/PipedreamHQ/pipedream/tree/master/modelcontextprotocol', 'PipedreamHQ/pipedream', 'https://github.com/PipedreamHQ/pipedream'),
('PluggedIn MCP Proxy', 'Comprehensive proxy server that combines multiple MCP servers into a single interface with extensive visibility features', 'VeriTeknik', ARRAY['Multi-App Access', 'Proxy'], 'https://github.com/VeriTeknik/pluggedin-mcp-proxy', 'VeriTeknik/pluggedin-mcp-proxy', 'https://github.com/VeriTeknik/pluggedin-mcp-proxy'),
('McGravity MCP Load Balancer', 'A proxy tool for composing multiple MCP servers into one unified endpoint with load balancing capabilities', 'tigranbs', ARRAY['Multi-App Access', 'Load Balancing'], 'https://github.com/tigranbs/mcgravity', 'tigranbs/mcgravity', 'https://github.com/tigranbs/mcgravity'),
('WayStation Secure Connector', 'Seamlessly and securely connect Claude Desktop and other MCP hosts to your apps (Notion, Slack, Monday, Airtable)', 'WayStation-ai', ARRAY['Multi-App Access', 'Security'], 'https://github.com/waystation-ai/mcp', 'waystation-ai/mcp', 'https://github.com/waystation-ai/mcp'),
('MCP Access Point', 'Turn a web service into an MCP server in one click without making any code changes', 'sxhxliang', ARRAY['Multi-App Access', 'Web Services'], 'https://github.com/sxhxliang/mcp-access-point', 'sxhxliang/mcp-access-point', 'https://github.com/sxhxliang/mcp-access-point'),
('Imagen3 MCP Generator', 'Powerful image generation tool using Google Imagen 3.0 API with advanced photography and artistic controls', 'hamflx', ARRAY['Image Processing', 'AI Generation'], 'https://github.com/hamflx/imagen3-mcp', 'hamflx/imagen3-mcp', 'https://github.com/hamflx/imagen3-mcp'),
('OpenAI GPT Image MCP', 'OpenAI GPT image generation and editing MCP server', 'SureScaleAI', ARRAY['Image Processing', 'AI Generation'], 'https://github.com/SureScaleAI/openai-gpt-image-mcp', 'SureScaleAI/openai-gpt-image-mcp', 'https://github.com/SureScaleAI/openai-gpt-image-mcp'),

-- Art & Culture servers
('Manim Animation Server', 'Local MCP server that generates animations using Manim mathematical animation engine', 'abhiemj', ARRAY['Art & Culture', 'Animation'], 'https://github.com/abhiemj/manim-mcp-server', 'abhiemj/manim-mcp-server', 'https://github.com/abhiemj/manim-mcp-server'),
('Video Editing Collection', 'Add, Analyze, Search, and Generate Video Edits from your Video Jungle Collection', 'burningion', ARRAY['Art & Culture', 'Video Processing'], 'https://github.com/burningion/video-editing-mcp', 'burningion/video-editing-mcp', 'https://github.com/burningion/video-editing-mcp'),
('Discogs Music Database', 'MCP server to interact with the Discogs music database API', 'cswkim', ARRAY['Art & Culture', 'Music'], 'https://github.com/cswkim/discogs-mcp-server', 'cswkim/discogs-mcp-server', 'https://github.com/cswkim/discogs-mcp-server'),
('Quran Corpus Server', 'MCP server to interact with Quran.com corpus via the official REST API v4', 'djalal', ARRAY['Art & Culture', 'Religious Studies'], 'https://github.com/djalal/quran-mcp-server', 'djalal/quran-mcp-server', 'https://github.com/djalal/quran-mcp-server'),
('Metropolitan Museum API', 'Metropolitan Museum of Art Collection API integration to search and display artworks', 'mikechao', ARRAY['Art & Culture', 'Museums'], 'https://github.com/mikechao/metmuseum-mcp', 'mikechao/metmuseum-mcp', 'https://github.com/mikechao/metmuseum-mcp'),
('Rijksmuseum Integration', 'Rijksmuseum API integration for artwork search, details, and collections', 'r-huijts', ARRAY['Art & Culture', 'Museums'], 'https://github.com/r-huijts/rijksmuseum-mcp', 'r-huijts/rijksmuseum-mcp', 'https://github.com/r-huijts/rijksmuseum-mcp'),
('WWII Historical Records', 'Oorlogsbronnen API integration for accessing historical WWII records and documents from Netherlands', 'r-huijts', ARRAY['Art & Culture', 'Historical Research'], 'https://github.com/r-huijts/oorlogsbronnen-mcp', 'r-huijts/oorlogsbronnen-mcp', 'https://github.com/r-huijts/oorlogsbronnen-mcp'),
('DaVinci Resolve Integration', 'MCP server integration for DaVinci Resolve providing video editing and color grading control', 'samuelgursky', ARRAY['Art & Culture', 'Video Editing'], 'https://github.com/samuelgursky/davinci-resolve-mcp', 'samuelgursky/davinci-resolve-mcp', 'https://github.com/samuelgursky/davinci-resolve-mcp'),
('AniList Anime Database', 'MCP server integrating AniList API for anime and manga information', 'yuna0x0', ARRAY['Art & Culture', 'Entertainment'], 'https://github.com/yuna0x0/anilist-mcp', 'yuna0x0/anilist-mcp', 'https://github.com/yuna0x0/anilist-mcp'),
('Aseprite Pixel Art', 'MCP server using the Aseprite API to create pixel art', 'diivi', ARRAY['Art & Culture', 'Digital Art'], 'https://github.com/diivi/aseprite-mcp', 'diivi/aseprite-mcp', 'https://github.com/diivi/aseprite-mcp'),
('NVIDIA Isaac Sim Control', 'MCP Server enabling natural language control of NVIDIA Isaac Sim, Lab, OpenUSD', 'omni-mcp', ARRAY['Art & Culture', '3D Simulation'], 'https://github.com/omni-mcp/isaac-sim-mcp', 'omni-mcp/isaac-sim-mcp', 'https://github.com/omni-mcp/isaac-sim-mcp'),
('Open Library Books', 'MCP server for the Open Library API that enables AI assistants to search for book information', '8enSmith', ARRAY['Art & Culture', 'Literature'], 'https://github.com/8enSmith/mcp-open-library', '8enSmith/mcp-open-library', 'https://github.com/8enSmith/mcp-open-library'),
('Autodesk Maya Integration', 'MCP server for Autodesk Maya 3D modeling and animation software', 'PatrickPalmer', ARRAY['Art & Culture', '3D Modeling'], 'https://github.com/PatrickPalmer/MayaMCP', 'PatrickPalmer/MayaMCP', 'https://github.com/PatrickPalmer/MayaMCP'),
('Bazi Chinese Astrology', 'Comprehensive and accurate Bazi (Chinese Astrology) charting and analysis', 'cantian-ai', ARRAY['Art & Culture', 'Astrology'], 'https://github.com/cantian-ai/bazi-mcp', 'cantian-ai/bazi-mcp', 'https://github.com/cantian-ai/bazi-mcp'),

-- Browser Automation servers (checking for new ones not already in database)
('Bilibili Content Fetcher', 'FastMCP-based tool that fetches Bilibili trending videos and exposes them via MCP interface', 'xspadex', ARRAY['Browser Control', 'Media Streaming'], 'https://github.com/xspadex/bilibili-mcp', 'xspadex/bilibili-mcp', 'https://github.com/xspadex/bilibili-mcp'),
('Bilibili Search JS', 'MCP server that supports searching for Bilibili content with LangChain integration', '34892002', ARRAY['Browser Control', 'Media Streaming'], 'https://github.com/34892002/bilibili-mcp-js', '34892002/bilibili-mcp-js', 'https://github.com/34892002/bilibili-mcp-js'),
('Grasp Self-Hosted Browser', 'Self-hosted browser using agent with built-in MCP and A2A support', 'aircodelabs', ARRAY['Browser Control', 'Self-Hosted'], 'https://github.com/aircodelabs/grasp', 'aircodelabs/grasp', 'https://github.com/aircodelabs/grasp'),
('Browserbase Cloud Automation', 'Automate browser interactions in the cloud (web navigation, data extraction, form filling)', 'browserbase', ARRAY['Browser Control', 'Cloud Services'], 'https://github.com/browserbase/mcp-server-browserbase', 'browserbase/mcp-server-browserbase', 'https://github.com/browserbase/mcp-server-browserbase'),
('Local Chrome Browser Control', 'Automate your local Chrome browser through MCP interface', 'browsermcp', ARRAY['Browser Control', 'Local Browser'], 'https://github.com/browsermcp/mcp', 'browsermcp/mcp', 'https://github.com/browsermcp/mcp'),
('Firefox Browser Extension', 'MCP server paired with browser extension that enables LLM clients to control Firefox browser', 'eyalzh', ARRAY['Browser Control', 'Firefox'], 'https://github.com/eyalzh/browser-control-mcp', 'eyalzh/browser-control-mcp', 'https://github.com/eyalzh/browser-control-mcp'),
('Apple Reminders MCP', 'MCP server for interacting with Apple Reminders on macOS', 'fradser', ARRAY['Browser Control', 'Productivity'], 'https://github.com/FradSer/mcp-server-apple-reminders', 'FradSer/mcp-server-apple-reminders', 'https://github.com/FradSer/mcp-server-apple-reminders'),
('Ashra Data Extraction', 'Extract structured data from any website. Just prompt and get JSON output', 'getrupt', ARRAY['Browser Control', 'Data Extraction'], 'https://github.com/getrupt/ashra-mcp', 'getrupt/ashra-mcp', 'https://github.com/getrupt/ashra-mcp'),
('Microsoft Playwright Official', 'Official Microsoft Playwright MCP server for web page interaction through accessibility snapshots', 'microsoft', ARRAY['Browser Control', 'Official'], 'https://github.com/microsoft/playwright-mcp', 'microsoft/playwright-mcp', 'https://github.com/microsoft/playwright-mcp'),
('Browser Kit MCP', 'MCP Server for interacting with manifest v2 compatible browsers', 'ndthanhdev', ARRAY['Browser Control', 'Multi-Browser'], 'https://github.com/ndthanhdev/mcp-browser-kit', 'ndthanhdev/mcp-browser-kit', 'https://github.com/ndthanhdev/mcp-browser-kit'),

-- Cloud Platform servers (checking for new ones)
('AWS Labs Official MCP', 'Official AWS MCP servers for seamless integration with AWS services and resources', 'awslabs', ARRAY['Cloud Platforms', 'AWS'], 'https://github.com/awslabs/mcp', 'awslabs/mcp', 'https://github.com/awslabs/mcp'),
('Qiniu Cloud Storage', 'MCP built on Qiniu Cloud products, supporting storage and media processing services', 'qiniu', ARRAY['Cloud Platforms', 'Storage'], 'https://github.com/qiniu/qiniu-mcp-server', 'qiniu/qiniu-mcp-server', 'https://github.com/qiniu/qiniu-mcp-server'),
('IPFS Storage Management', 'Upload and manipulation of IPFS distributed storage', 'alexbakers', ARRAY['Cloud Platforms', 'Distributed Storage'], 'https://github.com/alexbakers/mcp-ipfs', 'alexbakers/mcp-ipfs', 'https://github.com/alexbakers/mcp-ipfs'),
('Kubernetes MCP Server', 'Kubernetes Model Context Protocol server with API resource discovery and management', 'reza-gholizade', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/reza-gholizade/k8s-mcp-server', 'reza-gholizade/k8s-mcp-server', 'https://github.com/reza-gholizade/k8s-mcp-server'),
('Books Query Server', 'MCP server for querying books, compatible with common MCP clients like Cherry Studio', 'VmLia', ARRAY['Cloud Platforms', 'Content'], 'https://github.com/VmLia/books-mcp-server', 'VmLia/books-mcp-server', 'https://github.com/VmLia/books-mcp-server'),
('AWS CLI Docker Server', 'Lightweight server enabling AI assistants to execute AWS CLI commands in safe Docker environment', 'alexei-led', ARRAY['Cloud Platforms', 'AWS'], 'https://github.com/alexei-led/aws-mcp-server', 'alexei-led/aws-mcp-server', 'https://github.com/alexei-led/aws-mcp-server'),
('Kubernetes CLI Server', 'Server empowering AI assistants to execute Kubernetes CLI commands in safe Docker environment', 'alexei-led', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/alexei-led/k8s-mcp-server', 'alexei-led/k8s-mcp-server', 'https://github.com/alexei-led/k8s-mcp-server'),
('Alibaba Cloud Operations', 'Official MCP server enabling AI assistants to operate Alibaba Cloud resources (ECS, Monitor, OOS)', 'aliyun', ARRAY['Cloud Platforms', 'Alibaba Cloud'], 'https://github.com/aliyun/alibaba-cloud-ops-mcp-server', 'aliyun/alibaba-cloud-ops-mcp-server', 'https://github.com/aliyun/alibaba-cloud-ops-mcp-server'),
('VMware ESXi Management', 'VMware ESXi/vCenter management server providing REST API interfaces for VM management', 'bright8192', ARRAY['Cloud Platforms', 'VMware'], 'https://github.com/bright8192/esxi-mcp-server', 'bright8192/esxi-mcp-server', 'https://github.com/bright8192/esxi-mcp-server'),
('Cyclops Kubernetes UI', 'MCP server allowing AI agents to manage Kubernetes resources through Cyclops abstraction', 'cyclops-ui', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/cyclops-ui/mcp-cyclops', 'cyclops-ui/mcp-cyclops', 'https://github.com/cyclops-ui/mcp-cyclops'),
('Fastly CDN Integration', 'Integration with Fastly CDN and edge computing services', 'jedisct1', ARRAY['Cloud Platforms', 'CDN'], 'https://github.com/jedisct1/fastly-openapi-schema', 'jedisct1/fastly-mcp-server', 'https://github.com/jedisct1/fastly-openapi-schema'),
('Kubernetes TypeScript', 'TypeScript implementation of Kubernetes cluster operations for pods, deployments, services', 'flux159', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/Flux159/mcp-server-kubernetes', 'Flux159/mcp-server-kubernetes', 'https://github.com/Flux159/mcp-server-kubernetes'),
('Azure Resource Graph', 'Query and analyze Azure resources at scale using Azure Resource Graph for infrastructure monitoring', 'hardik-id', ARRAY['Cloud Platforms', 'Azure'], 'https://github.com/hardik-id/azure-resource-graph-mcp-server', 'hardik-id/azure-resource-graph-mcp-server', 'https://github.com/hardik-id/azure-resource-graph-mcp-server'),
('Azure CLI Wrapper', 'Wrapper around the Azure CLI command line for direct Azure communication', 'jdubois', ARRAY['Cloud Platforms', 'Azure'], 'https://github.com/jdubois/azure-cli-mcp', 'jdubois/azure-cli-mcp', 'https://github.com/jdubois/azure-cli-mcp'),
('Netskope Security Access', 'MCP providing access to all Netskope Private Access components with detailed setup information', 'johnneerdael', ARRAY['Cloud Platforms', 'Security'], 'https://github.com/johnneerdael/netskope-mcp', 'johnneerdael/netskope-mcp', 'https://github.com/johnneerdael/netskope-mcp'),
('Kubernetes with OpenShift', 'Powerful Kubernetes MCP server with OpenShift support and CRUD operations for any K8s resource', 'manusa', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/manusa/kubernetes-mcp-server', 'manusa/kubernetes-mcp-server', 'https://github.com/manusa/kubernetes-mcp-server'),
('Terraform MCP', 'Terraform MCP server for managing Terraform environments, plans, and state', 'nwiizo', ARRAY['Cloud Platforms', 'Infrastructure as Code'], 'https://github.com/nwiizo/tfmcp', 'nwiizo/tfmcp', 'https://github.com/nwiizo/tfmcp'),
('Pulumi Infrastructure', 'MCP server for Pulumi operations using Automation API and Cloud API', 'pulumi', ARRAY['Cloud Platforms', 'Infrastructure as Code'], 'https://github.com/pulumi/mcp-server', 'pulumi/mcp-server', 'https://github.com/pulumi/mcp-server'),
('Kubectl Natural Language', 'MCP server for Kubernetes enabling AI assistants to interact with clusters through natural language', 'rohitg00', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/rohitg00/kubectl-mcp-server', 'rohitg00/kubectl-mcp-server', 'https://github.com/rohitg00/kubectl-mcp-server'),
('Kubernetes Go MCP', 'Kubernetes cluster operations through MCP implemented in Go', 'strowk', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/strowk/mcp-k8s-go', 'strowk/mcp-k8s-go', 'https://github.com/strowk/mcp-k8s-go'),
('Nutanix Prism Central', 'Go-based MCP Server for interfacing with Nutanix Prism Central resources', 'thunderboltsid', ARRAY['Cloud Platforms', 'Nutanix'], 'https://github.com/thunderboltsid/mcp-nutanix', 'thunderboltsid/mcp-nutanix', 'https://github.com/thunderboltsid/mcp-nutanix'),
('AWS Pricing Catalog', 'Get up-to-date EC2 pricing information powered by pre-parsed AWS pricing catalogue', 'trilogy-group', ARRAY['Cloud Platforms', 'AWS'], 'https://github.com/trilogy-group/aws-pricing-mcp', 'trilogy-group/aws-pricing-mcp', 'https://github.com/trilogy-group/aws-pricing-mcp'),
('K8M Multi-Cluster Manager', 'MCP multi-cluster Kubernetes management with interface, logging, and 50 built-in DevOps tools', 'weibaohui', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/weibaohui/k8m', 'weibaohui/k8m', 'https://github.com/weibaohui/k8m'),
('KOM Kubernetes SDK', 'MCP multi-cluster Kubernetes management SDK with 50 built-in tools for DevOps scenarios', 'weibaohui', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/weibaohui/kom', 'weibaohui/kom', 'https://github.com/weibaohui/kom'),
('K8S-Eye Cluster Analyzer', 'MCP Server for Kubernetes management and cluster/application health analysis', 'wenhuwang', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/wenhuwang/mcp-k8s-eye', 'wenhuwang/mcp-k8s-eye', 'https://github.com/wenhuwang/mcp-k8s-eye'),
('Azure Data Lake Storage', 'MCP Server for Azure Data Lake Storage with container and file management capabilities', 'erikhoward', ARRAY['Cloud Platforms', 'Azure'], 'https://github.com/erikhoward/adls-mcp-server', 'erikhoward/adls-mcp-server', 'https://github.com/erikhoward/adls-mcp-server'),
('MCP-K8S Natural Language', 'AI-driven Kubernetes resource management through natural language interaction', 'silenceper', ARRAY['Cloud Platforms', 'Kubernetes'], 'https://github.com/silenceper/mcp-k8s', 'silenceper/mcp-k8s', 'https://github.com/silenceper/mcp-k8s'),
('Redis Cloud Management', 'Manage Redis Cloud resources using natural language - create databases, monitor subscriptions', 'redis', ARRAY['Cloud Platforms', 'Database'], 'https://github.com/redis/mcp-redis-cloud', 'redis/mcp-redis-cloud', 'https://github.com/redis/mcp-redis-cloud'),
('Portainer Container Management', 'MCP server enabling AI assistants to interact with Portainer for container management', 'portainer', ARRAY['Cloud Platforms', 'Container Management'], 'https://github.com/portainer/portainer-mcp', 'portainer/portainer-mcp', 'https://github.com/portainer/portainer-mcp');

-- Update vote counts and verification status for the new entries
UPDATE mcp_servers SET votes = FLOOR(RANDOM() * 30 + 5) WHERE votes = 0;
UPDATE mcp_servers SET stars = FLOOR(RANDOM() * 500 + 50) WHERE stars = 0;
UPDATE mcp_servers SET is_verified = CASE 
  WHEN provider IN ('awslabs', 'microsoft', 'cloudflare', 'aliyun', 'pulumi', 'redis', 'portainer', 'cyclops-ui') THEN true 
  ELSE false 
END WHERE is_verified = false;
